# Generated by Django 4.2.18 on 2025-10-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='created_by',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('USER', 'User')], max_length=50, null=True),
        ),
    ]
